Repository AY2021S1-CS2103T-W13-1/tp, pull requests merged in 2020-10, with the labels that each got.

#51 add leave class
  src/main/java/com/eva/commons/util/DateUtil.java
  src/main/java/com/eva/commons/util/IntegerUtil.java
  src/main/java/com/eva/model/person/staff/Staff.java
  src/main/java/com/eva/model/person/staff/leave/DefaultLeaveBalance.java
  src/main/java/com/eva/model/person/staff/leave/Leave.java
  src/main/java/com/eva/model/person/staff/leave/LeaveBalance.java
Labels: hacktoberfest-accepted

#104 Set use case headings for standardization in DG
  docs/DeveloperGuide.md
Labels: priority.High

#103 Add edit commands
  src/main/java/com/eva/logic/commands/EditCommand.java
  src/main/java/com/eva/logic/parser/EditCommandParser.java
  src/main/java/com/eva/logic/parser/ParserUtil.java
  src/main/java/com/eva/model/comment/Comment.java
  src/main/java/com/eva/storage/JsonAdaptedComment.java
  src/test/java/com/eva/logic/commands/EditCommandTest.java
  src/test/java/com/eva/logic/parser/EditCommandParserTest.java
  src/test/java/com/eva/logic/parser/EvaParserTest.java
Labels: priority.High, type.Story

#109 Update UG formatting and specific commands + Fix README links
  README.md
  docs/UserGuide.md
Labels: priority.High

#127 Add delapplication command functionality
  src/main/java/com/eva/logic/commands/DeleteApplicationCommand.java
  src/main/java/com/eva/logic/parser/DeleteApplicationCommandParser.java
  src/main/java/com/eva/logic/parser/EvaParser.java
  src/main/java/com/eva/model/Model.java
  src/main/java/com/eva/model/ModelManager.java
  src/test/java/com/eva/logic/commands/AddCommandTest.java
Labels: priority.High

#131 Update application functional aspects
  src/main/java/com/eva/logic/commands/AddApplicationCommand.java
  src/main/java/com/eva/logic/commands/DeleteApplicantCommand.java
  src/main/java/com/eva/logic/parser/AddApplicationCommandParser.java
  src/main/java/com/eva/model/person/applicant/application/Application.java
Labels: priority.High
